In [1]:
import pandas as pd
#df = pd.read_csv(r'https://raw.githubusercontent.com/nerdyphil/ML-Study-Group/master/Assignment/raw_fighter_details.csv')
df = pd.read_csv(r'https://raw.githubusercontent.com/nerdyphil/ML-Study-Group/master/Assignment/raw_total_fight_data.csv', sep=';', engine='python')
top = df.head(5)
bottom = df.tail(5)
top

              R_fighter  ...                Winner
0          Henry Cejudo  ...          Henry Cejudo
1  Valentina Shevchenko  ...  Valentina Shevchenko
2         Tony Ferguson  ...         Tony Ferguson
3         Jimmie Rivera  ...              Petr Yan
4           Tai Tuivasa  ...         Blagoy Ivanov

[5 rows x 41 columns]

In [2]:
bottom

           R_fighter      B_fighter  ...        Fight_type          Winner
5139  Gerard Gordeau   Kevin Rosier  ...  Open Weight Bout  Gerard Gordeau
5140    Ken Shamrock  Patrick Smith  ...  Open Weight Bout    Ken Shamrock
5141    Royce Gracie  Art Jimmerson  ...  Open Weight Bout    Royce Gracie
5142    Kevin Rosier   Zane Frazier  ...  Open Weight Bout    Kevin Rosier
5143  Gerard Gordeau     Teila Tuli  ...  Open Weight Bout  Gerard Gordeau

[5 rows x 41 columns]

In [3]:
print("".join(i+"\n" for i in df.columns.values))

R_fighter
B_fighter
R_KD
B_KD
R_SIG_STR.
B_SIG_STR.
R_SIG_STR_pct
B_SIG_STR_pct
R_TOTAL_STR.
B_TOTAL_STR.
R_TD
B_TD
R_TD_pct
B_TD_pct
R_SUB_ATT
B_SUB_ATT
R_PASS
B_PASS
R_REV
B_REV
R_HEAD
B_HEAD
R_BODY
B_BODY
R_LEG
B_LEG
R_DISTANCE
B_DISTANCE
R_CLINCH
B_CLINCH
R_GROUND
B_GROUND
win_by
last_round
last_round_time
Format
Referee
date
location
Fight_type
Winner

In [4]:
print(df.shape)

(5144, 41)

In [5]:
index_4 = df.loc[3,:]
index_4

R_fighter                   Jimmie Rivera
B_fighter                        Petr Yan
R_KD                                    0
B_KD                                    2
R_SIG_STR.                      73 of 192
B_SIG_STR.                      56 of 189
R_SIG_STR_pct                         38%
B_SIG_STR_pct                         29%
R_TOTAL_STR.                    76 of 195
B_TOTAL_STR.                    58 of 192
R_TD                               0 of 3
B_TD                               1 of 3
R_TD_pct                               0%
B_TD_pct                              33%
R_SUB_ATT                               0
B_SUB_ATT                               0
R_PASS                                  0
B_PASS                                  1
R_REV                                   0
B_REV                                   0
R_HEAD                          42 of 145
B_HEAD                          40 of 166
R_BODY                           15 of 24
B_BODY                           13 of 19
R_LEG                            16 of 23
B_LEG                              3 of 4
R_DISTANCE                      60 of 173
B_DISTANCE                      42 of 167
R_CLINCH                          9 of 15
B_CLINCH                         10 of 12
R_GROUND                           4 of 4
B_GROUND                          4 of 10
win_by               Decision - Unanimous
last_round                              3
last_round_time                      5:00
Format                      3 Rnd (5-5-5)
Referee                   Kevin MacDonald
date                        June 08, 2019
location           Chicago, Illinois, USA
Fight_type              Bantamweight Bout
Winner                           Petr Yan
Name: 3, dtype: object

In [6]:
df.describe()

              R_KD         B_KD  ...        B_REV   last_round
count  5144.000000  5144.000000  ...  5144.000000  5144.000000
mean      0.252333     0.180404  ...     0.134137     2.288297
std       0.523318     0.459646  ...     0.416798     1.003732
min       0.000000     0.000000  ...     0.000000     1.000000
25%       0.000000     0.000000  ...     0.000000     1.000000
50%       0.000000     0.000000  ...     0.000000     3.000000
75%       0.000000     0.000000  ...     0.000000     3.000000
max       5.000000     4.000000  ...     3.000000     5.000000

[8 rows x 9 columns]

In [7]:
Q1 = df.quantile(0.25)  
Q3 = df.quantile(0.75)
IQR = Q3 - Q1
outliers = (df < (Q1 - 1.5 * IQR)) |(df > (Q3 + 1.5 * IQR))
print(outliers)

      B_BODY  B_CLINCH  B_DISTANCE  ...  last_round_time  location  win_by
0      False     False       False  ...            False     False   False
1      False     False       False  ...            False     False   False
2      False     False       False  ...            False     False   False
3      False     False       False  ...            False     False   False
4      False     False       False  ...            False     False   False
...      ...       ...         ...  ...              ...       ...     ...
5139   False     False       False  ...            False     False   False
5140   False     False       False  ...            False     False   False
5141   False     False       False  ...            False     False   False
5142   False     False       False  ...            False     False   False
5143   False     False       False  ...            False     False   False

[5144 rows x 41 columns]

In [8]:
df.fillna(0)

                 R_fighter  ...                Winner
0             Henry Cejudo  ...          Henry Cejudo
1     Valentina Shevchenko  ...  Valentina Shevchenko
2            Tony Ferguson  ...         Tony Ferguson
3            Jimmie Rivera  ...              Petr Yan
4              Tai Tuivasa  ...         Blagoy Ivanov
...                    ...  ...                   ...
5139        Gerard Gordeau  ...        Gerard Gordeau
5140          Ken Shamrock  ...          Ken Shamrock
5141          Royce Gracie  ...          Royce Gracie
5142          Kevin Rosier  ...          Kevin Rosier
5143        Gerard Gordeau  ...        Gerard Gordeau

[5144 rows x 41 columns]

In [9]:
df.corr(method ='pearson')

                R_KD      B_KD  R_SUB_ATT  ...     R_REV     B_REV  last_round
R_KD        1.000000 -0.110068  -0.108992  ... -0.073842 -0.070521   -0.164803
B_KD       -0.110068  1.000000  -0.095970  ... -0.046033 -0.037023   -0.046165
R_SUB_ATT  -0.108992 -0.095970   1.000000  ...  0.227679  0.170480    0.015192
B_SUB_ATT  -0.093408 -0.037095   0.046162  ...  0.215045  0.218857    0.106363
R_PASS     -0.113336 -0.106515   0.336716  ...  0.204033  0.267956    0.225454
B_PASS     -0.125981 -0.026231   0.066240  ...  0.298298  0.234291    0.209167
R_REV      -0.073842 -0.046033   0.227679  ...  1.000000  0.330921    0.132709
B_REV      -0.070521 -0.037023   0.170480  ...  0.330921  1.000000    0.146903
last_round -0.164803 -0.046165   0.015192  ...  0.132709  0.146903    1.000000

[9 rows x 9 columns]

In [0]:
df.to_csv(r'../processed_data_week2.ipynb')